### ISSUE TITLE
Problem with ffi

### ISSUE THREAD

**Issue by scooler** [ricktessner/butane#6]
I've had this issue:
https://github.com/ffi/ffi/issues/94

Gemfile.lock requires 1.0.7 and it worked for me with 1.0.11

**Comment by ricktessner** [comment]
I'll try and make some time this coming weekend to take a look at it.

**Comment by ricktessner** [comment]
Updated to work with the latest versions of the gems. If there's still problems, please open a new issue. Thanks!
