### ISSUE TITLE
Problem with Faraday/tinder

### ISSUE THREAD

**Issue by scooler** [ricktessner/butane#7]
Similar to [issue #6](https://github.com/ricktessner/butane/issues/6) this is the "hard" dependency issue:

issue in tinder:
https://github.com/collectiveidea/tinder/issues/21

and it's in the Gemfile.lock

however when I removed Gemfile.lock and run bundle install (to get newest versions) - some other error occurred (looks like tinder changed it's api :( )

I also tried setting version of tinder to "1.6.0" - it also caused butane to crash :( - so I guess code has to be touched, but no time for that now.

**Comment by ricktessner** [comment]
I'll try and make some time this coming weekend to take a look at this one as well. Thanks!

**Comment by ricktessner** [comment]
Updated to use the latest gems. Working with tinder 1.8.0. If there's any issues, please open a new issue. Thanks!
